class_descriptions:
  0: Vehicle - Các phương tiện giao thông khác (car, vehicle chung)
  1: Bus - Xe buýt, xe khách
  2: Bicycle - Xe đạp các loại
  3: Person - Người (đi bộ, ngồi trên xe, tất cả người)
  4: Engine - Xe 2 bánh có động cơ (motorcycle, scooter)
  5: Truck - Xe tải các loại
  6: Tricycle - Xe 3 bánh
  7: Obstacle - Vật cản, chướng ngại vật
  8: Pothole - Ổ gà, hư hỏng mặt đường
  9: Traffic Light - Đèn giao thông
  10: Traffic Sign - Biển báo giao thông (bao gồm 29 biển VN + các biển khác)
classes:
- Vehicle
- Bus
- Bicycle
- Person
- Engine
- Truck
- Tricycle
- Obstacle
- Pothole
- Traffic Light
- Traffic Sign
created_date: '2025-09-20'
dataset_info:
  intersection_flow_5k:
    description: Traffic intersection surveillance data
    estimated_annotations: 400000
    total_classes: 8
    traffic_classes_used: 6
  object_detection_35:
    description: VisionGuard dataset with 35 object classes for blind assistance
    total_annotations: 23043
    total_classes: 35
    traffic_annotations: 7503
    traffic_classes_used: 11
  road_issues:
    description: Road infrastructure problems dataset
    total_classes: 7
    total_images: 9660
    traffic_classes_used: 2
  vn_traffic_sign:
    description: Vietnamese traffic signs dataset
    estimated_annotations: 2800
    total_classes: 29
    traffic_classes_used: 1
description: 11-class taxonomy theo đề xuất user - tối ưu cho giao thông Việt Nam
mapping:
  intersection_flow_5k:
    0: 3  # pedestrian -> Person
    1: 2  # bicycle -> Bicycle
    2: 0  # vehicle -> Vehicle
    3: 0  # car -> Vehicle
    4: 5  # truck -> Truck
    5: 1  # bus -> Bus
    6: 4  # engine -> Engine
    7: 6  # tricycle -> Tricycle
  object_detection_35:
    0: 3   # Person -> Person
    10: 1  # Bus -> Bus
    12: 2  # Bicycle -> Bicycle
    14: 5  # Truck -> Truck
    15: 4  # Motorcycles -> Engine
    20: 9  # Traffic Light -> Traffic Light
    23: 10 # Stop Sign -> Traffic Sign
    24: 0  # Car -> Vehicle
    25: 7  # Barriers -> Obstacle
    26: 8  # Path Holes -> Pothole
    28: 0  # Train -> Vehicle (or could be separate if needed)
  road_issues:
    0: 10  # broken_road_sign -> Traffic Sign
    4: 8   # pothole -> Pothole
  vn_traffic_sign:
    all_classes: 10  # All traffic signs -> Traffic Sign
num_classes: 11
project_name: Traffic AI YOLOv12 - 11-Class Taxonomy theo đề xuất User
training_strategy:
  augmentation_focus:
  - 4  # Engine
  - 6  # Tricycle  
  - 7  # Obstacle
  - 8  # Pothole
  - 9  # Traffic Light
  class_weights: inverse_frequency
  data_balance:
    high_priority:
    - 0  # Vehicle
    - 3  # Person
    - 9  # Traffic Light
    - 10 # Traffic Sign
    low_priority:
    - 6  # Tricycle
    - 7  # Obstacle
    - 8  # Pothole
    medium_priority:
    - 1  # Bus
    - 2  # Bicycle
    - 4  # Engine
    - 5  # Truck
version: '2.0'
